name: Upload to Dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Upload to SFTP
      uses: milanmk/actions-file-deployer@master
      with:
          remote-protocol: "sftp"
          remote-host: ${{ secrets.FTP_IP }}
          remote-port: ${{ secrets.FTP_PORT }}
          remote-user: ${{ secrets.FTP_PASSWORD }}
          remote-password: ${{ secrets.FTP_PASSWORD }}
          remote-path: "/data/odyssey/txData/server/resources/[scripts]/br_utils"